export const data = [
	{
		id: 1,
		name: 'Neapolitana',
		description:
			'Dough made of four types of flour, Shredded Pelati tomatoes, Mozzarella, Parmesan',
		price: 360,
		img: 'https://php.ninjapizza.com.ua/images/157/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: false,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 2,
		name: 'Carbonara',
		description:
			'Dough made of four types of flour, Mozzarella, Parmesan, Crispy fried onion',
		price: 340,
		img: 'https://php.ninjapizza.com.ua/images/21/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: false,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 3,
		name: 'Margherita',
		description:
			'Dough made of four types of flour, Shredded Pelati tomatoes, Mozzarella, Cherry tomato',
		price: 300,
		img: 'https://php.ninjapizza.com.ua/images/9/l2x.webp?ver=v1.0.7',
		isVegan: true,
		isSpicy: true,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 4,
		name: 'Cheeseburger',
		description:
			'Dough made of four types of flour, Whipped cream sauce, Cheddar, Boiled veal',
		price: 440,
		img: 'https://php.ninjapizza.com.ua/images/16/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: false,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 5,
		name: 'Tom Yam',
		description:
			'Dough made of four types of flour, Whipped cream sauce, Mozzarella, Tom Yam paste',
		price: 500,
		img: 'https://php.ninjapizza.com.ua/images/5/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: true,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 6,
		name: 'Pepperoni ',
		description:
			'Dough made of four types of flour, Shredded Pelati tomatoes, Mozzarella, Salami Napoli',
		price: 340,
		img: 'https://php.ninjapizza.com.ua/images/1/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: true,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 7,
		name: 'Sweet Chilli Chicken ',
		description:
			'Dough made of four types of flour, Whipped cream sauce, Mozzarella, Smoked chicken fillet',
		price: 360,
		img: 'https://php.ninjapizza.com.ua/images/8/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: false,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
	{
		id: 8,
		name: 'Amore',
		description:
			'Dough made of four types of flour, Mozzarella, Parmesan, Balsamic cream',
		price: 380,
		img: 'https://php.ninjapizza.com.ua/images/26/l2x.webp?ver=v1.0.7',
		isVegan: false,
		isSpicy: false,
		isSale: false,
		salePrice: null,
		isNew: false,
	},
]
